### ISSUE TITLE
Fixes before merging licsense check PR

### ISSUE THREAD

**Issue by doki-nordic** [doki-nordic/fw-nrfconnect-nrf#10]
Things that should be checked/done before merging https://github.com/nrfconnect/sdk-nrf/pull/8022:
* [ ] Fix typos in commit message (during squashing)
* [ ] Add JIRA Ref to commit message (during squashing)
* [ ] Reconsider breaking error line into two lines to avoid repeating file name in the annotation.
* [x] Verify if the change log entry is really required for this PR

**Comment by thst-nordic** [comment]
change log is not needed for this, the label is just applied so that you think about it. 
👍
